# 缺失值处理

In [1]:
from sklearn.preprocessing import Imputer

In [3]:
df = DataFrame(np.random.randn(6,4),columns=['col1','col2','col3','col4'])
df.iloc[1:2,1] = np.nan
df.iloc[4,3] = np.nan
df

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465       NaN  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129       NaN
5 -0.388217 -1.110050  1.012914 -0.960552

In [4]:
df.isnull()

col1   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False

In [6]:
nan_model = Imputer(missing_values='NaN',strategy='mean',axis=0)
nan_result = nan_model.fit_transform(df)
nan_result

array([[ 2.18434061,  1.58190059,  0.83035621,  0.60905845],
       [-1.34746547,  0.20008323,  0.78959733,  1.35756791],
       [ 1.5307302 ,  0.69271874,  0.76107174,  0.80892494],
       [-0.20085478, -0.88117029, -0.84651227, -1.5298816 ],
       [-1.55016995,  0.7170172 ,  0.5351291 ,  0.05702361],
       [-0.38821708, -1.11005008,  1.01291378, -0.96055165]])

In [9]:
nan_result_pd1 = df.fillna(method='backfill')
nan_result_pd2 = df.fillna(method='bfill',limit=1)
nan_result_pd3 = df.fillna(method='pad')
nan_result_pd4 = df.fillna(0)
nan_result_pd5 = df.fillna({'col2':1.1,'col4':1.4})
nan_result_pd6 = df.fillna(df.mean()['col2':'col4'])
nan_result_pd1
nan_result_pd2
nan_result_pd3
nan_result_pd4
nan_result_pd5
nan_result_pd6

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465  0.692719  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129 -0.960552
5 -0.388217 -1.110050  1.012914 -0.960552

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465  0.692719  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129 -0.960552
5 -0.388217 -1.110050  1.012914 -0.960552

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465  1.581901  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129 -1.529882
5 -0.388217 -1.110050  1.012914 -0.960552

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465  0.000000  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129  0.000000
5 -0.388217 -1.110050  1.012914 -0.960552

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465  1.100000  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129  1.400000
5 -0.388217 -1.110050  1.012914 -0.960552

col1      col2      col3      col4
0  2.184341  1.581901  0.830356  0.609058
1 -1.347465  0.200083  0.789597  1.357568
2  1.530730  0.692719  0.761072  0.808925
3 -0.200855 -0.881170 -0.846512 -1.529882
4 -1.550170  0.717017  0.535129  0.057024
5 -0.388217 -1.110050  1.012914 -0.960552

# 异常值处理

In [11]:
df = DataFrame({'col1':[1,120,3,5,2,12,13],
               'col2':[12,17,31,53,22,32,43]})
df

col1  col2
0     1    12
1   120    17
2     3    31
3     5    53
4     2    22
5    12    32
6    13    43

In [13]:
((df - df.mean())/df.std()).abs()
((df - df.mean())/df.std()).abs() > 2.2

col1      col2
0  0.491018  1.242118
1  2.254069  0.897085
2  0.444882  0.069007
3  0.398746  1.587151
4  0.467950  0.552052
5  0.237270  0.138013
6  0.214202  0.897085

col1   col2
0  False  False
1   True  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False

# 重复值处理


In [14]:
data1 = ['a', 3]
data2 = ['b', 2]
data3 = ['a', 3]
data4 = ['c', 2]
df = pd.DataFrame([data1, data2, data3, data4], columns=['col1', 'col2'])
df

col1  col2
0    a     3
1    b     2
2    a     3
3    c     2

In [17]:
df.duplicated(keep='first')

0    False
1    False
2     True
3    False
dtype: bool

In [18]:
df.drop_duplicates()  # 删除数据记录中所有列值相同的记录
df.drop_duplicates(['col1'])  # 删除数据记录中col1值相同的记录
df.drop_duplicates(['col2'])  # 删除数据记录中col2值相同的记录
df.drop_duplicates(['col1', 'col2'])  # 删除数据记录中指定列（col1/col2）值相同的记录

col1  col2
0    a     3
1    b     2
3    c     2

col1  col2
0    a     3
1    b     2
3    c     2

col1  col2
0    a     3
1    b     2

col1  col2
0    a     3
1    b     2
3    c     2

# 运用标志方法处理分类和顺序数据

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
df = pd.DataFrame({'id': [3566841, 6541227, 3512441],
                   'sex': ['male', 'Female', 'Female'],
                   'level': ['high', 'low', 'middle']})
print (df)  # 打印输出原始数据框

# 自定义转换主过程
df_new = df.copy()  # 复制一份新的数据框用来存储转换结果
for col_num, col_name in enumerate(df):  # 循环读出每个列的索引值和列名
    col_data = df[col_name]  # 获得每列数据
    col_dtype = col_data.dtype  # 获得每列dtype类型
    if col_dtype == 'object':  # 如果dtype类型是object（非数值型），执行条件
        df_new = df_new.drop(col_name, 1)  # 删除df数据框中要进行标志转换的列
        value_sets = col_data.unique()  # 获取分类和顺序变量的唯一值域
        for value_unique in value_sets:  # 读取分类和顺序变量中的每个值
            col_name_new = col_name + '_' + value_unique  # 创建新的列名，使用原标题+值的方式命名
            col_tmp = df.iloc[:, col_num]  # 获取原始数据列
            new_col = (col_tmp == value_unique)  # 将原始数据列与每个值进行比较，相同为True，否则为False
            df_new[col_name_new] = new_col  # 为最终结果集增加新列值
print (df_new)  # 打印输出转换后的数据框

        id     sex   level
0  3566841    male    high
1  6541227  Female     low
2  3512441  Female  middle
        id  sex_male  sex_Female  level_high  level_low  level_middle
0  3566841      True       False        True      False         False
1  6541227     False        True       False       True         False
2  3512441     False        True       False      False          True


In [31]:
# 使用sklearn进行标志转换
df2 = pd.DataFrame({'id': [3566841, 6541227, 3512441],
                    'sex': [1, 2, 2],
                    'level': [3, 1, 2]})
id_data = df2.values[:, :1]  # 获得ID列
transform_data = df2.values[:, 1:]  # 指定要转换的列
enc = OneHotEncoder()  # 建立模型对象
df2_new = enc.fit_transform(transform_data).toarray()  # 标志转换
df2_all = pd.concat((pd.DataFrame(id_data), pd.DataFrame(df2_new)), axis=1)  # 组合为数据框
print (df2_all)  # 打印输出转换后的数据框

         0    0    1    2    3    4
0  3566841  1.0  0.0  0.0  0.0  1.0
1  6541227  0.0  1.0  1.0  0.0  0.0
2  3512441  0.0  1.0  0.0  1.0  0.0


# 降维

## 基于特征选择的降维

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.decomposition import PCA

In [3]:
data = np.loadtxt('./datacode_for_book/chapter3/data1.txt')
x = data[:,:-1]
y = data[:,-1]

In [7]:
model_tree = DecisionTreeClassifier(random_state=0)
model_tree.fit(x,y)
model_tree.feature_importances_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

array([ 0.03331054,  0.01513967,  0.02199713,  0.119727  ,  0.47930312,
        0.04776297,  0.17111746,  0.02585441,  0.02012725,  0.06566044])

## 基于维度转化的降维

In [9]:
model_pca = PCA()
model_pca.fit(x)
model_pca.transform(x)
model_pca.components_ #获得转换后的所有主成分
model_pca.explained_variance_ #转换后各主成分方差
model_pca.explained_variance_ratio_ #转换后各主成分方差占比

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

array([[ -7.14927818e-01,  -1.28423732e+00,   9.70941426e-02, ...,
          8.49862907e-01,  -3.85828738e-17,   4.08671706e-17],
       [  4.53144795e+00,   8.94878501e-01,   1.43687773e-01, ...,
         -9.68730619e-01,   6.82705353e-16,  -1.25938218e-16],
       [ -2.26234301e+00,   2.02927993e+00,  -1.64956276e+00, ...,
          8.78685187e-01,  -2.10041553e-16,   6.76676253e-17],
       ..., 
       [  1.67848551e+00,   1.85832563e+00,   1.92665769e+00, ...,
          8.60429575e-01,  -5.13924223e-16,  -3.83615520e-16],
       [  2.26445904e+00,  -1.81967438e+00,  -2.08053649e+00, ...,
          1.64953682e-01,   3.08157423e-16,   1.64345963e-16],
       [ -1.46084060e+00,   9.23766684e-01,   9.60664147e-02, ...,
          3.25635502e-01,  -3.16855376e-16,   1.61369745e-17]])

array([[  7.18818316e-03,   1.41619205e-02,   1.00543847e-02,
          3.65097575e-01,   6.38944537e-01,  -1.95750380e-02,
         -1.73413378e-01,  -3.80829974e-02,  -2.87413113e-03,
         -6.52829504e-01],
       [  1.01307710e-02,  -1.95270201e-04,  -2.33689543e-02,
         -6.12915216e-01,   5.08983971e-01,  -2.23429533e-02,
          6.02958940e-01,  -1.49061329e-02,  -1.81362216e-02,
         -3.41623971e-03],
       [  2.42092694e-01,  -3.68867909e-01,   8.69351030e-02,
         -7.00211582e-03,  -1.29243443e-02,  -1.85568410e-01,
          3.19371656e-03,  -5.45736371e-01,   6.81990577e-01,
          1.29862924e-02],
       [ -5.37952093e-01,  -3.20020806e-01,   5.71456215e-01,
         -6.04075415e-03,   5.35156139e-03,  -4.92373002e-01,
          6.00870251e-03,   1.94978861e-01,  -3.29057598e-02,
         -2.66614329e-04],
       [ -2.91882846e-02,  -4.75039025e-01,   9.53825483e-03,
          5.00110135e-03,  -1.65709576e-02,   1.71776210e-01,
         -7.36820709e-03

array([  4.22602937e+00,   2.21149972e+00,   1.11509461e+00,
         1.09123938e+00,   1.02864637e+00,   1.00339950e+00,
         9.21917768e-01,   8.92677850e-01,   6.44164910e-32,
         1.15507238e-32])

array([  3.38339364e-01,   1.77054475e-01,   8.92753857e-02,
         8.73655166e-02,   8.23542686e-02,   8.03329836e-02,
         7.38094896e-02,   7.14685179e-02,   5.15723689e-33,
         9.24760387e-34])

# 解决样本类别不均衡的问题

In [30]:
import imblearn

ModuleNotFoundError: No module named 'imblearn'

In [28]:
df = pd.read_csv('./datacode_for_book/chapter3/data2.txt',sep=' ',names=['col1','col2','col3','col4','col5','label'])
df.head()

col1      col2      col3      col4      col5  label
0  1.484710 -0.567953  0.957248 -1.028711 -1.143092    0.0
1 -1.021847 -0.209943  0.585039 -0.625991 -0.532367    0.0
2 -0.418176  0.878976 -0.333351  0.371767  1.223683    0.0
3  0.441664  1.405135  2.334376 -2.453234  0.594130    0.0
4 -1.855857  1.342565  1.457096 -1.522041  0.935034    0.0

In [29]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
df.groupby('label').count()

col1  col2  col3  col4  col5
label                              
0.0     942   942   942   942   942
1.0      58    58    58    58    58